services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
      POSTGRES_DB: ${DB_NAME:-bookandride}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-app} -d ${DB_NAME:-bookandride}"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    env_file:
       - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://app:app@db:5432/bookandride}
      ELASTICSEARCH_URL: http://elasticsearch:9200 # Elastic Search URL
    ports:
       - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health', timeout=3).read()"]
      interval: 5s
      timeout: 3s
      retries: 20

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      api:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml:ro
      depends_on:
        - api
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  dbdata:
  grafana_data:
