{
 "title": "Book &  Ride - Real-time Mobitoring",
 "time": { "from": "2025-12-01T09:29:26.794Z", "to": "2025-12-01T11:24:20.050Z" },
 "panels": [
  {
   "title": "RPS per path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Error Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n sum(rate(http_requests_total{status=~\"404\"}[5m]))\r\n /\r\n sum(rate(http_requests_total[5m]))\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Rental Price (EUR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n 0.95,\r\n sum(rate(bookandride_rental_price_eur_bucket[10m])) by (le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Rentals Now",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bookandride_active_rentals", "legendFormat": "__auto" }
   ]
  }
 ]
}