pipeline { 
    agent any 
 
    stages { 
 
        stage('Checkout Book & Ride Code') { 
            steps { 
                git branch: 'dev', url: 'https://github.com/rdrio02/BookAndRide.git' 
            } 
        } 
 
        stage('Install Dependencies') { 
            steps { 
                sh ''' 
                python3 -m venv venv
                . venv/bin/activate

                pip install --upgrade pip
                pip install build

                # Install package + dependencies defined in pyproject.toml
                pip install ".[dev]"
                ''' 
            } 
        } 
 
        stage('Run Book & Ride Tests') { 
            steps { 
                sh ''' 
                . venv/bin/activate 
                pytest -q 
                ''' 
            } 
        } 
 
        stage('Build Package (sdist + wheel)') { 
            steps { 
                sh ''' 
                . venv/bin/activate 
                pip install build 
                python -m build 
                ''' 
            } 
        } 

    } 
    post { 
        success { 
            echo 'Book & Ride CI pipeline completed successfully!' 
        } 
        failure { 
            echo 'Book & Ride CI pipeline failed.' 
        } 
    } 
} 